### ISSUE TITLE
Memory usage (PyTorch)

### ISSUE THREAD

**Issue by cile98** [yongchao97/FRePo#4]
Hello Yongchao, 

When running the script for PyTorch (using the commands from the readme, only with distill_torch) the process gets killed often because it runs out of memory - both on my local machine(approx after ~50K iterations) and on the cluster(after 200K iterations). Could it be that there is some kind of memory leakage? When restarting the process it continues from the checkpoint without any issues.  

Thank you in advance for your help!
Best, Jovan

**Comment by yongchao97** [comment]
Hi Jovan,

Could you provide a bit more details? For example, Pytorch version, CUDA version, GPU info, CPU memory.

It was fine when I tested on T4 GPU with 15GB memory. Driver Version: 470.103.01, CUDA Version: 11.4, CPU memory 32GB, Pytorch Version: py3.10_cuda11.3_cudnn8.3.2_0.

Thanks,
Yongchao

**Comment by cile98** [comment]
Sorry for the long reply, here is the info: On the local machine: 16GB RAM, GeForce RTX 2060 Mobile with 6GB,  PyTorch 1.11.0,  CUDA 10.2. Here is also the plot of RAM usage at every iteration of the distilling 
![ram](https://user-images.githubusercontent.com/23198302/201319503-6f4fd8ca-ebfa-4cb3-87ca-d64748bb8c11.png)

**Comment by cile98** [comment]
On the cluster: PyTorch 1.11.0+cu102,  Cuda 10.2, RTX 2080TI
![ram1](https://user-images.githubusercontent.com/23198302/201321408-5b3f1f43-e675-41c4-9550-f51df65fb6ae.png)

**Comment by yongchao97** [comment]
Hi Jovan,

I look at the RAM usage using the following code and plot the memory vs. step below. I do not observe the memory leakage problem, but I observe the memory increase after each evaluation (~100MB increase). Therefore, the memory leakage problem may be due to the PyTorch or CUDA version problem. You may want to update your environment. As for the latter issue, I borrowed the evaluation code from the DC repo. A simple workaround is to evaluate less frequently by changing `steps_per_eval` to some larger value (Default: 10000). Let me know if you have any further questions.

Best,
Yongchao

```
def process_memory():
    process = psutil.Process(os.getpid())
    mem_info = process.memory_info()
    return mem_info.rss / 1024 / 1024
```

![memory](https://user-images.githubusercontent.com/29878668/201491160-c4bdc764-7568-4ae8-b416-ceb33cbd4bdb.png)
